export const UPDATE_MOVIES = 'UPDATE_MOVIES'
export const UPDATE_SEARCH_BY = 'UPDATE_SEARCH_BY'
export const UPDATE_SELECTED_ITEM = 'UPDATE_SELECTED_ITEM'
export const UPDATE_SORT_BY = 'UPDATE_SORT_BY'
export const UPDATE_SEARCH_TEXT = 'UPDATE_SEARCH_TEXT'
export const LOADING = 'LOADING'

